import { defineConfig } from 'cspell'

const config = defineConfig({
  dictionaries: [
    'ada',
    'al',
    'aws',
    'bash',
    'companies',
    'cpp',
    'cryptocurrencies',
    'csharp',
    'css',
    'dart',
    'data-science',
    'django',
    'docker',
    'dotnet',
    'elixir',
    'en-common-misspellings',
    'en-gb',
    'en_us',
    'filetypes',
    'flutter',
    'fonts',
    'fsharp',
    'fullstack',
    'gaming-terms',
    'git',
    'golang',
    'google',
    'haskell',
    'html',
    'html-symbol-entities',
    'java',
    'julia',
    'k8s',
    'kotlin',
    'latex',
    'lorem-ipsum',
    'lua',
    'makefile',
    'markdown',
    'monkeyc',
    'node',
    'npm',
    'php',
    'powershell',
    'public-licenses',
    'python',
    'r',
    'ruby',
    'rust',
    'scala',
    'shell',
    'software-terms',
    'sql',
    'svelte',
    'swift',
    'terraform',
    'typescript',
    'vue',
    'custom-words',
  ],
  dictionaryDefinitions: [
    {
      addWords: true,
      description: 'Custom words dictionary.',
      name: 'custom-words',
      path: '.cspell/custom-words.txt',
    },
  ],
  import: [
    '@cspell/dict-ada',
    '@cspell/dict-al',
    '@cspell/dict-aws',
    '@cspell/dict-bash',
    '@cspell/dict-companies',
    '@cspell/dict-cpp',
    '@cspell/dict-cryptocurrencies',
    '@cspell/dict-csharp',
    '@cspell/dict-css',
    '@cspell/dict-dart',
    '@cspell/dict-data-science',
    '@cspell/dict-django',
    '@cspell/dict-docker',
    '@cspell/dict-dotnet',
    '@cspell/dict-elixir',
    '@cspell/dict-en-common-misspellings',
    '@cspell/dict-en-gb',
    '@cspell/dict-en_us',
    '@cspell/dict-filetypes',
    '@cspell/dict-flutter',
    '@cspell/dict-fonts',
    '@cspell/dict-fsharp',
    '@cspell/dict-fullstack',
    '@cspell/dict-gaming-terms',
    '@cspell/dict-git',
    '@cspell/dict-golang',
    '@cspell/dict-google',
    '@cspell/dict-haskell',
    '@cspell/dict-html',
    '@cspell/dict-html-symbol-entities',
    '@cspell/dict-java',
    '@cspell/dict-julia',
    '@cspell/dict-k8s',
    '@cspell/dict-kotlin',
    '@cspell/dict-latex',
    '@cspell/dict-lorem-ipsum',
    '@cspell/dict-lua',
    '@cspell/dict-makefile',
    '@cspell/dict-markdown',
    '@cspell/dict-monkeyc',
    '@cspell/dict-node',
    '@cspell/dict-npm',
    '@cspell/dict-php',
    '@cspell/dict-powershell',
    '@cspell/dict-public-licenses',
    '@cspell/dict-python',
    '@cspell/dict-r',
    '@cspell/dict-ruby',
    '@cspell/dict-rust',
    '@cspell/dict-scala',
    '@cspell/dict-shell',
    '@cspell/dict-software-terms',
    '@cspell/dict-sql',
    '@cspell/dict-svelte',
    '@cspell/dict-swift',
    '@cspell/dict-terraform',
    '@cspell/dict-typescript',
    '@cspell/dict-vue',
  ],
  readonly: true,
  useGitignore: true,
})

export default config
